 plugins {

    // Android Gradle Plugin
    id 'com.android.application' version '9.2.1' apply false
    id 'com.android.library' version '9.2.1' apply false

    // Kotlin
    id 'org.jetbrains.kotlin.android' version '2.3.21' apply false

    // KSP
    id 'com.google.devtools.ksp' version '2.3.8' apply false

    // Hilt
    id 'com.google.dagger.hilt.android' version '2.59.2' apply false

    // Kotlin Serialization
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.3.21' apply false

    // Compose Compiler Plugin
    id 'org.jetbrains.kotlin.plugin.compose' version '2.3.21' apply false
}